title: "Chavez Cyrillus Mariae Poon"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
show_excerpts: false
show_frame: true

navigation:
  - {file: "index.md"}
  - {file: "about.md"}
  - {file: "publications.md"}
  - {file: "contact.md"}
  - {file: "blog.html"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jektex
