title: "Chavez Cyrillus Mariae Poon"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
show_excerpts: false
show_frame: true

navigation:
  - {file: "index.md"}
  - {file: "about.md"}
  - {file: "publications.md"}
  - {file: "contact.md"}
  - {file: "blog.html"}
  - {title: 中文, url: "/zh-hk/"}

external:
  - {title: Color, icon: moon, url: "javascript:toggle()"}
  - {title: Github, icon: github, url: "https://github.com/poonlonghei/", target="_blank"}
  - {title: Feed, icon: rss, url: "/feed.xml", target="_blank"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jektex

future: true
