title: "Chavez Cyrillus Mariae Poon"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
show_excerpts: false
show_frame: true

navigation:
  - {file: "index.md"}
  - {file: "about.md"}
  - {file: "publications.md"}
  - {file: "contact.md"}
  - {file: "blog.html"}
  - {title: 中文, url: "/zh-hk/"}

external:
  - {title: Color, icon: moon, url: "javascript:toggle()"}
  - {title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jektex

future: true

footer:
  enable_footer: true
  footer_description: "Powered by Jekyll with contrast theme, Histed by Github Pages"
  copyright_text: "Copyright © 2025 Chavez Cyrillus Mariae Poon. All rights reserved."
